# run command:
# docker compose --env-file .env up

# volumes:
#   database-v:
#     name: "database-v"

services:
  fiscalismia-postgres:
    image: ${POSTGRES_HOST}:1.0.0
    container_name: ${POSTGRES_HOST}
    build:
      context: .
      dockerfile: database/Dockerfile.db
    env_file:
      - path: .env
        required: true
    # volumes:
    #   - database-v:/var/lib/postgresql/data
    networks:
      - fiscalismia-network
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: "-p ${POSTGRES_PORT}"
    # to use healthcheck for backend server see https://wittcode.com/blogs/connect-a-node-server-to-postgres-with-docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  fiscalismia-network:
    name: fiscalismia-network
    driver: bridge

# to connect to db in attached docker shell, (RUN apk add --no-cache postgresql-client):
# psql -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES_HOST -p $POSTGRES_PORT
# to connect from local machine, the host has to be localhost!
# psql -U $POSTGRES_USER -d $POSTGRES_DB -h localhost -p $POSTGRES_PORT