# Stage 1 INSTALL
FROM node:20.12.2-alpine3.19
WORKDIR /fiscalismia-backend/
COPY LICENSE package-lock.json package.json tsconfig.json ./
RUN npm install
COPY src/ ./src
ENTRYPOINT ["npm", "run", "server"]
# tests folder later for workflow
# public in docker-compose / docker-run mounten