# docker build --pull --rm -f "Dockerfile" -t fiscalismia-backend:latest "."
# docker run -v %cd%\public:/fiscalismia-backend/public --env-file .env --rm -it -p 3002:3002 --name fiscalismia-backend fiscalismia-backend:latest