#       _
#    __| | _____   __
#   / _` |/ _ \ \ / /
#  | (_| |  __/\ V /
#   \__,_|\___| \_/
# docker build --pull --rm -f "Dockerfile.dev" -t fiscalismia-backend-dev:latest "."
# docker run -v %cd%\public:/fiscalismia-backend/public --env-file .env --rm -it -p 3002:3002 --name fiscalismia-backend-dev fiscalismia-backend-dev:latest
#                       _
#   _ __  _ __ ___   __| |
#  | '_ \| '__/ _ \ / _` |
#  | |_) | | | (_) | (_| |
#  | .__/|_|  \___/ \__,_|
#  |_|
# docker build --pull --rm -f "Dockerfile.prod" -t fiscalismia-backend-prod:latest "."
# docker run -v %cd%\public:/fiscalismia-backend/public --env-file .env --rm -it -p 3002:3002 --name fiscalismia-backend-prod fiscalismia-backend-prod:latest