#       _
#    __| | _____   __
#   / _` |/ _ \ \ / /
#  | (_| |  __/\ V /
#   \__,_|\___| \_/
# docker build --pull --rm -f "Dockerfile.dev" -t fiscalismia-backend-dev:latest "."
# docker run -v %cd%\public:/fiscalismia-backend/public --env-file .env --rm -it -p 3002:3002 --name fiscalismia-backend-dev fiscalismia-backend-dev:latest
#                       _
#   _ __  _ __ ___   __| |
#  | '_ \| '__/ _ \ / _` |
#  | |_) | | | (_) | (_| |
#  | .__/|_|  \___/ \__,_|
#  |_|
# docker build --pull --rm -f "Dockerfile" -t fiscalismia-backend:latest "."
# docker run -v %cd%\public:/fiscalismia-backend/public --env-file .env --rm -it -p 3002:3002 --name fiscalismia-backend fiscalismia-backend:latest

# run command:
# docker compose --env-file .env up

# volumes:
#   database-v:
#     name: "database-v"

services:
  fiscalismia-database:
    image: fiscalismia-database:1.0.0
    container_name: fiscalismia-database
    build:
      context: .
      dockerfile: database/Dockerfile.db
    env_file:
      - path: .env
        required: true
    # volumes:
    #   - database-v:/var/lib/postgresql/data
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: "-p ${POSTGRES_PORT}"
    # to use healthcheck for backend server see https://wittcode.com/blogs/connect-a-node-server-to-postgres-with-docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
# to connect to db in attached docker shell run:
# psql -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES_HOST -p $POSTGRES_PORT