# run command:
# docker compose --env-file .env up

# volumes:
#   database-v:
#     name: "database-v"

services:
  fiscalismia-database:
    image: fiscalismia-database:1.0.0
    container_name: fiscalismia-database
    build:
      context: .
      dockerfile: database/Dockerfile.db
    env_file:
      - path: .env
        required: true
    # volumes:
    #   - database-v:/var/lib/postgresql/data
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: "-p ${POSTGRES_PORT}"
    # to use healthcheck for backend server see https://wittcode.com/blogs/connect-a-node-server-to-postgres-with-docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
# networks:
#   fiscalismia-network:
#     external: true
# to connect to db in attached docker shell run:
# psql -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES_HOST -p $POSTGRES_PORT