name: Fiscalismia-Backend Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.3-alpine3.20
        env:
          POSTGRES_USER: fiscalismia_api
          #default is already localhost
          #POSTGRES_HOST: localhost
          POSTGRES_DB: fiscalismia
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: |
        npm ci
        npm i -g snyk

    - name: Compiler Type Checks
      run: npm run typeCheck

    - name: Eslint Analysis
      run: npm run eslintAnalysis

    # - name: Snyk Static Code Security Analysis
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   run: |
    #     snyk auth $SNYK_TOKEN
    #     npm run snykCodeAnalysis

    # - name: Snyk Dependency Security Analysis
    #   run: npm run snykDependencyAnalysis

    - name: Publish Typecheck & Eslint & Snyk Reports
      uses: actions/upload-artifact@v4
      with:
        name: Fiscalismia-Backend-Reports
        path: |
          reports/
          !reports/.gitkeep

    - name: Initialize Database
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
          PG_CONNECTION="-h localhost -U fiscalismia_api -d fiscalismia"
          USER_SCHEMA="private_admin"
          SEARCH_PATH_CMD="SET search_path TO $USER_SCHEMA, public"

          psql $PG_CONNECTION <<-EOSQL
            CREATE SCHEMA IF NOT EXISTS $USER_SCHEMA AUTHORIZATION fiscalismia_api;
            GRANT ALL ON SCHEMA $USER_SCHEMA TO fiscalismia_api;
          EOSQL

          psql $PG_CONNECTION -c "$SEARCH_PATH_CMD; \c fiscalismia" -f database/pgsql-global-ddl.sql

          psql $PG_CONNECTION <<-EOSQL
            SET client_encoding TO 'UTF8';

            INSERT INTO public.um_users (username, email, password, schema) VALUES
            ('admin',
            'herp_derp@hotmail.com',
            crypt( 'changeit', gen_salt('bf',12)),
            'private_admin'
            );

            INSERT INTO public.um_user_settings(
            user_id, setting_key, setting_value, setting_description)
            VALUES (
                (SELECT id FROM public.um_users WHERE username = 'admin'),
                'selected_mode',
                'light',
                null);

            INSERT INTO public.um_user_settings(
            user_id, setting_key, setting_value, setting_description)
            VALUES (
                (SELECT id FROM public.um_users WHERE username = 'admin'),
                'selected_palette',
                'default',
                null);

            INSERT INTO public.um_user_settings(
            user_id, setting_key, setting_value, setting_description)
            VALUES (
                (SELECT id FROM public.um_users WHERE username = 'admin'),
                'selected_language',
                'en_US',
                null);
          EOSQL
          psql $PG_CONNECTION -c "$SEARCH_PATH_CMD; \c fiscalismia" -f database/pgsql-global-dml.sql

    - name: REST API tests /w supertest
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        POSTGRES_USER: fiscalismia_api
        #this .env variable is only needed in docker-development, otherwise defaults to localhost in src\utils\pgDbService.ts
        #POSTGRES_HOST: localhost
        POSTGRES_DB: fiscalismia
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT: 5432
      run: npm test

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build --pull --rm -f "Dockerfile" -t ghcr.io/hangrybear666/fiscalismia-backend:latest "."

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Docker Image to GHCR
      run: docker push ghcr.io/hangrybear666/fiscalismia-backend:latest


